class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startx'
        self.MirrorCommand = 'mirrorx'
        self.UnzipMirrorCommand = 'unzipx'
        self.TarMirrorCommand = 'tarx'
        self.CancelMirror = 'cancelx'
        self.CancelAllCommand = 'cnlallx'
        self.ListCommand = 'listx'
        self.StatusCommand = 'statusx'
        self.AuthorizeCommand = 'authx'
        self.UnAuthorizeCommand = 'unauthx'
        self.PingCommand = 'pingx'
        self.RestartCommand = 'restartx'
        self.StatsCommand = 'statx'
        self.HelpCommand = 'hlpx'
        self.LogCommand = 'logx'
        self.SpeedCommand = 'speedtestx'
        self.CloneCommand = 'clonex'
        self.WatchCommand = 'watchx'
        self.TarWatchCommand = 'tarwatchx'
        self.DeleteCommand = 'delx'
        self.UsageCommand = 'usagex'
        self.RepoCommand = 'repox'

BotCommands = _BotCommands()
